using System;
using System.Collections.Generic;
using System.IO;
using Redpenguin.GoogleSheets.Editor.Utils;
using UnityEditor;
using UnityEngine;

namespace Redpenguin.GoogleSheets.Editor.Factories
{
  public class SpreadSheetScriptableObjectFactory : IAutoGenFactory
  {
    public bool Create(List<Type> types, string profileName)
    {
      if(types.Count == 0) return false;
      var savePath = $"{Application.dataPath}/GoogleSheets/{profileName}/Resources/SheetsSO";
      if (!Directory.Exists(savePath))
      {
        Directory.CreateDirectory(savePath);
      }
      foreach (var type in types)
      {
        var asset = ScriptableObject.CreateInstance(type);
        AssetDatabase.CreateAsset(asset, $"Assets/GoogleSheets/{profileName}/Resources/SheetsSO/{type.Name}.asset");
      }
      AssetDatabase.SaveAssets();
      AssetDatabase.Refresh();
      
      Debug.Log("Scriptable Objects was created!".WithColor(ColorExt.CompletedColor));
      return true;
    }

    public bool Delete(string profileName)
    {
      return AssetDatabase.DeleteAsset($"Assets/GoogleSheets/AutoGenerated/{profileName}/Resources/SheetsSO");
    }
  }
}